// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface CandlesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.Candles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Candle candles = 1;</code>
   */
  java.util.List<Candle>
      getCandlesList();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Candle candles = 1;</code>
   */
  Candle getCandles(int index);
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Candle candles = 1;</code>
   */
  int getCandlesCount();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Candle candles = 1;</code>
   */
  java.util.List<? extends CandleOrBuilder>
      getCandlesOrBuilderList();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Candle candles = 1;</code>
   */
  CandleOrBuilder getCandlesOrBuilder(
      int index);
}
