// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface ChartListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.ChartList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Chart charts = 1;</code>
   */
  java.util.List<Chart>
      getChartsList();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Chart charts = 1;</code>
   */
  Chart getCharts(int index);
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Chart charts = 1;</code>
   */
  int getChartsCount();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Chart charts = 1;</code>
   */
  java.util.List<? extends ChartOrBuilder>
      getChartsOrBuilderList();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Chart charts = 1;</code>
   */
  ChartOrBuilder getChartsOrBuilder(
      int index);
}
