// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public final class CoinService {
  private CoinService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_Chart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_Chart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_Plot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_Plot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_ChartList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_ChartList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_Candle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_Candle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_Candles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_Candles_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_CandleMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_CandleMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_BtcDomCandleMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_BtcDomCandleMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_ConfigEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_ConfigEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateBackTestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_CandleMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_CandleMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_BtcDomCandleMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_BtcDomCandleMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_ConfigEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_ConfigEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_StreamCandleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_StreamCandleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetSignalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetSignalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetSignalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetSignalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CreateOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CreateOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CancelOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CancelOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coin_algorithm_grpc_service_generated_CancelOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coin_algorithm_grpc_service_generated_CancelOrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022coin_service.proto\022%coin.algorithm.grp" +
      "c.service.generated\"\237\001\n\005Chart\022\021\n\tisOverl" +
      "ay\030\001 \001(\010\022\014\n\004name\030\002 \001(\t\022\027\n\017backgroundColo" +
      "r\030\003 \001(\t\022\r\n\005width\030\004 \001(\005\022\016\n\006height\030\005 \001(\005\022=" +
      "\n\010plotList\030\006 \003(\0132+.coin.algorithm.grpc.s" +
      "ervice.generated.Plot\"\217\001\n\004Plot\022\014\n\004name\030\001" +
      " \001(\t\022\r\n\005color\030\002 \001(\t\022?\n\005style\030\003 \001(\01620.coi" +
      "n.algorithm.grpc.service.generated.PlotS" +
      "tyle\022\026\n\016pricePrecision\030\004 \001(\005\022\021\n\tvalueLis" +
      "t\030\005 \003(\002\"I\n\tChartList\022<\n\006charts\030\001 \003(\0132,.c" +
      "oin.algorithm.grpc.service.generated.Cha" +
      "rt\"\255\001\n\006Candle\022\021\n\tstartTime\030\001 \001(\003\022\017\n\007endT" +
      "ime\030\002 \001(\003\022\014\n\004open\030\003 \001(\001\022\r\n\005close\030\004 \001(\001\022\014" +
      "\n\004high\030\005 \001(\001\022\013\n\003low\030\006 \001(\001\022\016\n\006volume\030\007 \001(" +
      "\001\022\020\n\010duration\030\010 \001(\003\022\025\n\risCloseCandle\030\t \001" +
      "(\010\022\016\n\006symbol\030\n \001(\t\"I\n\007Candles\022>\n\007candles" +
      "\030\001 \003(\0132-.coin.algorithm.grpc.service.gen" +
      "erated.Candle\"\214\001\n\rTradeMetadata\022\r\n\005price" +
      "\030\001 \001(\001\022\016\n\006amount\030\002 \001(\001\022\027\n\017takeProfitPric" +
      "e\030\003 \001(\001\022\031\n\021takeStopLossPrice\030\004 \001(\001\022\020\n\010tr" +
      "adeLog\030\005 \001(\t\022\026\n\016waitingMinutes\030\006 \001(\003\"\276\005\n" +
      "\025CreateBackTestRequest\022?\n\007candles\030\001 \001(\0132" +
      "..coin.algorithm.grpc.service.generated." +
      "Candles\022^\n\tcandleMap\030\002 \003(\0132K.coin.algori" +
      "thm.grpc.service.generated.CreateBackTes" +
      "tRequest.CandleMapEntry\022j\n\017btcDomCandleM" +
      "ap\030\003 \003(\0132Q.coin.algorithm.grpc.service.g" +
      "enerated.CreateBackTestRequest.BtcDomCan" +
      "dleMapEntry\022\016\n\006symbol\030\004 \001(\t\022\026\n\016pricePrec" +
      "ision\030\005 \001(\005\022\031\n\021quantityPrecision\030\006 \001(\005\022\020" +
      "\n\010tickSize\030\007 \001(\005\022\024\n\014botOrderType\030\010 \001(\005\022\031" +
      "\n\021isEnableCloseMode\030\t \001(\010\022\017\n\007initBar\030\n \001" +
      "(\005\022\023\n\013initBalance\030\013 \001(\001\022\020\n\010makerFee\030\014 \001(" +
      "\001\022\020\n\010takerFee\030\r \001(\001\032`\n\016CandleMapEntry\022\013\n" +
      "\003key\030\001 \001(\005\022=\n\005value\030\002 \001(\0132..coin.algorit" +
      "hm.grpc.service.generated.Candles:\0028\001\032f\n" +
      "\024BtcDomCandleMapEntry\022\013\n\003key\030\001 \001(\005\022=\n\005va" +
      "lue\030\002 \001(\0132..coin.algorithm.grpc.service." +
      "generated.Candles:\0028\001\"\313\003\n\026CreateOnlineRu" +
      "nRequest\022\020\n\010exchange\030\001 \001(\t\022\024\n\014mainInterv" +
      "al\030\002 \001(\005\022\026\n\016otherIntervals\030\003 \003(\005\022\027\n\017btcD" +
      "omIntervals\030\017 \003(\005\022\016\n\006symbol\030\004 \001(\t\022\026\n\016pri" +
      "cePrecision\030\005 \001(\005\022\031\n\021quantityPrecision\030\006" +
      " \001(\005\022\020\n\010tickSize\030\007 \001(\005\022\024\n\014botOrderType\030\010" +
      " \001(\005\022\031\n\021isEnableCloseMode\030\t \001(\010\022\017\n\007initB" +
      "ar\030\n \001(\005\022\023\n\013initBalance\030\013 \001(\001\022\020\n\010makerFe" +
      "e\030\014 \001(\001\022\020\n\010takerFee\030\r \001(\001\022Y\n\006config\030\016 \003(" +
      "\0132I.coin.algorithm.grpc.service.generate" +
      "d.CreateOnlineRunRequest.ConfigEntry\032-\n\013" +
      "ConfigEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\",\n\026CreateBackTestResponse\022\022\n\nbackTes" +
      "tId\030\001 \001(\t\"\375\003\n\024CreateOnlineResponse\022\020\n\010on" +
      "lineId\030\001 \001(\t\022?\n\007candles\030\002 \001(\0132..coin.alg" +
      "orithm.grpc.service.generated.Candles\022]\n" +
      "\tcandleMap\030\003 \003(\0132J.coin.algorithm.grpc.s" +
      "ervice.generated.CreateOnlineResponse.Ca" +
      "ndleMapEntry\022i\n\017btcDomCandleMap\030\004 \003(\0132P." +
      "coin.algorithm.grpc.service.generated.Cr" +
      "eateOnlineResponse.BtcDomCandleMapEntry\032" +
      "`\n\016CandleMapEntry\022\013\n\003key\030\001 \001(\005\022=\n\005value\030" +
      "\002 \001(\0132..coin.algorithm.grpc.service.gene" +
      "rated.Candles:\0028\001\032f\n\024BtcDomCandleMapEntr" +
      "y\022\013\n\003key\030\001 \001(\005\022=\n\005value\030\002 \001(\0132..coin.alg" +
      "orithm.grpc.service.generated.Candles:\0028" +
      "\001\"\262\001\n\024GetTimeTravelRequest\022\022\n\nbackTestId" +
      "\030\001 \001(\t\022W\n\006config\030\002 \003(\0132G.coin.algorithm." +
      "grpc.service.generated.GetTimeTravelRequ" +
      "est.ConfigEntry\032-\n\013ConfigEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\272\001\n\025GetTimeTravel" +
      "Response\022\017\n\007buySell\030\001 \003(\005\022K\n\rtradeMetada" +
      "ta\030\002 \003(\01324.coin.algorithm.grpc.service.g" +
      "enerated.TradeMetadata\022C\n\tchartList\030\003 \001(" +
      "\01320.coin.algorithm.grpc.service.generate" +
      "d.ChartList\"K\n\027GetTradeMetadataRequest\022\020" +
      "\n\010onlineId\030\001 \001(\t\022\021\n\ttradeType\030\002 \001(\005\022\013\n\003i" +
      "dx\030\003 \001(\005\"y\n\030GetTradeMetadataResponse\022\020\n\010" +
      "onlineId\030\001 \001(\t\022K\n\rtradeMetadata\030\002 \001(\01324." +
      "coin.algorithm.grpc.service.generated.Tr" +
      "adeMetadata\"\'\n\023StreamCandleRequest\022\020\n\010on" +
      "lineId\030\001 \001(\t\"g\n\024StreamCandleResponse\022=\n\006" +
      "candle\030\001 \001(\0132-.coin.algorithm.grpc.servi" +
      "ce.generated.Candle\022\020\n\010onlineId\030\004 \001(\t\"1\n" +
      "\020GetSignalRequest\022\020\n\010onlineId\030\001 \001(\t\022\013\n\003i" +
      "dx\030\002 \001(\005\"C\n\021GetSignalResponse\022\r\n\005isBuy\030\001" +
      " \001(\010\022\016\n\006isSell\030\002 \001(\010\022\017\n\007isClose\030\003 \001(\010\"8\n" +
      "\025GetOrderStatusRequest\022\016\n\006symbol\030\002 \001(\t\022\017" +
      "\n\007orderId\030\001 \001(\t\"\200\001\n\026GetOrderStatusRespon" +
      "se\022B\n\006status\030\001 \001(\01622.coin.algorithm.grpc" +
      ".service.generated.OrderStatus\022\021\n\tisSucc" +
      "ess\030\003 \001(\010\022\017\n\007payload\030\002 \001(\t\"\326\001\n\022CreateOrd" +
      "erRequest\022\017\n\007orderId\030\001 \001(\t\022\016\n\006symbol\030\002 \001" +
      "(\t\022>\n\004side\030\003 \001(\01620.coin.algorithm.grpc.s" +
      "ervice.generated.OrderSide\022>\n\004type\030\004 \001(\016" +
      "20.coin.algorithm.grpc.service.generated" +
      ".OrderType\022\r\n\005price\030\005 \001(\t\022\020\n\010quantity\030\006 " +
      "\001(\t\"q\n\023CreateOrderResponse\022\017\n\007orderId\030\001 " +
      "\001(\t\022\016\n\006status\030\002 \001(\t\022\021\n\tisSuccess\030\003 \001(\010\022\017" +
      "\n\007payload\030\004 \001(\t\022\025\n\rexecutedPrice\030\005 \001(\t\"5" +
      "\n\022CancelOrderRequest\022\017\n\007orderId\030\001 \001(\t\022\016\n" +
      "\006symbol\030\002 \001(\t\"\216\001\n\023CancelOrderResponse\022\017\n" +
      "\007orderId\030\001 \001(\t\022B\n\006status\030\002 \001(\01622.coin.al" +
      "gorithm.grpc.service.generated.OrderStat" +
      "us\022\021\n\tisSuccess\030\003 \001(\010\022\017\n\007payload\030\004 \001(\t*!" +
      "\n\tPlotStyle\022\010\n\004LINE\020\000\022\n\n\006COLUMN\020\001*\036\n\tOrd" +
      "erSide\022\007\n\003BUY\020\000\022\010\n\004SELL\020\001*@\n\tOrderType\022\n" +
      "\n\006MARKET\020\000\022\t\n\005LIMIT\020\001\022\r\n\tSL_MARKET\020\002\022\r\n\t" +
      "TP_MARKET\020\003*a\n\013OrderStatus\022\007\n\003NEW\020\000\022\024\n\020P" +
      "ARTIALLY_FILLED\020\001\022\n\n\006FILLED\020\002\022\014\n\010CANCELE" +
      "D\020\003\022\014\n\010REJECTED\020\005\022\013\n\007EXPIRED\020\0062\226\n\n\024CoinA" +
      "lgorithmService\022\214\001\n\rGetTimeTravel\022;.coin" +
      ".algorithm.grpc.service.generated.GetTim" +
      "eTravelRequest\032<.coin.algorithm.grpc.ser" +
      "vice.generated.GetTimeTravelResponse\"\000\022\217" +
      "\001\n\016CreateBackTest\022<.coin.algorithm.grpc." +
      "service.generated.CreateBackTestRequest\032" +
      "=.coin.algorithm.grpc.service.generated." +
      "CreateBackTestResponse\"\000\022\217\001\n\017CreateOnlin" +
      "eRun\022=.coin.algorithm.grpc.service.gener" +
      "ated.CreateOnlineRunRequest\032;.coin.algor" +
      "ithm.grpc.service.generated.CreateOnline" +
      "Response\"\000\022\225\001\n\020GetTradeMetadata\022>.coin.a" +
      "lgorithm.grpc.service.generated.GetTrade" +
      "MetadataRequest\032?.coin.algorithm.grpc.se" +
      "rvice.generated.GetTradeMetadataResponse" +
      "\"\000\022\213\001\n\014StreamCandle\022:.coin.algorithm.grp" +
      "c.service.generated.StreamCandleRequest\032" +
      ";.coin.algorithm.grpc.service.generated." +
      "StreamCandleResponse\"\0000\001\022\200\001\n\tGetSignal\0227" +
      ".coin.algorithm.grpc.service.generated.G" +
      "etSignalRequest\0328.coin.algorithm.grpc.se" +
      "rvice.generated.GetSignalResponse\"\000\022\217\001\n\016" +
      "GetOrderStatus\022<.coin.algorithm.grpc.ser" +
      "vice.generated.GetOrderStatusRequest\032=.c" +
      "oin.algorithm.grpc.service.generated.Get" +
      "OrderStatusResponse\"\000\022\206\001\n\013CreateOrder\0229." +
      "coin.algorithm.grpc.service.generated.Cr" +
      "eateOrderRequest\032:.coin.algorithm.grpc.s" +
      "ervice.generated.CreateOrderResponse\"\000\022\206" +
      "\001\n\013CancelOrder\0229.coin.algorithm.grpc.ser" +
      "vice.generated.CancelOrderRequest\032:.coin" +
      ".algorithm.grpc.service.generated.Cancel" +
      "OrderResponse\"\000B\037\n\033coin.algorithm.grpc.s" +
      "erviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_coin_algorithm_grpc_service_generated_Chart_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coin_algorithm_grpc_service_generated_Chart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_Chart_descriptor,
        new String[] { "IsOverlay", "Name", "BackgroundColor", "Width", "Height", "PlotList", });
    internal_static_coin_algorithm_grpc_service_generated_Plot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_coin_algorithm_grpc_service_generated_Plot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_Plot_descriptor,
        new String[] { "Name", "Color", "Style", "PricePrecision", "ValueList", });
    internal_static_coin_algorithm_grpc_service_generated_ChartList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_coin_algorithm_grpc_service_generated_ChartList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_ChartList_descriptor,
        new String[] { "Charts", });
    internal_static_coin_algorithm_grpc_service_generated_Candle_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_coin_algorithm_grpc_service_generated_Candle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_Candle_descriptor,
        new String[] { "StartTime", "EndTime", "Open", "Close", "High", "Low", "Volume", "Duration", "IsCloseCandle", "Symbol", });
    internal_static_coin_algorithm_grpc_service_generated_Candles_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_coin_algorithm_grpc_service_generated_Candles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_Candles_descriptor,
        new String[] { "Candles", });
    internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_descriptor,
        new String[] { "Price", "Amount", "TakeProfitPrice", "TakeStopLossPrice", "TradeLog", "WaitingMinutes", });
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_descriptor,
        new String[] { "Candles", "CandleMap", "BtcDomCandleMap", "Symbol", "PricePrecision", "QuantityPrecision", "TickSize", "BotOrderType", "IsEnableCloseMode", "InitBar", "InitBalance", "MakerFee", "TakerFee", });
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_CandleMapEntry_descriptor =
      internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_descriptor.getNestedTypes().get(0);
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_CandleMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_CandleMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_BtcDomCandleMapEntry_descriptor =
      internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_descriptor.getNestedTypes().get(1);
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_BtcDomCandleMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateBackTestRequest_BtcDomCandleMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_descriptor,
        new String[] { "Exchange", "MainInterval", "OtherIntervals", "BtcDomIntervals", "Symbol", "PricePrecision", "QuantityPrecision", "TickSize", "BotOrderType", "IsEnableCloseMode", "InitBar", "InitBalance", "MakerFee", "TakerFee", "Config", });
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_ConfigEntry_descriptor =
      internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_descriptor.getNestedTypes().get(0);
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_ConfigEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateOnlineRunRequest_ConfigEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_coin_algorithm_grpc_service_generated_CreateBackTestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateBackTestResponse_descriptor,
        new String[] { "BackTestId", });
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_descriptor,
        new String[] { "OnlineId", "Candles", "CandleMap", "BtcDomCandleMap", });
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_CandleMapEntry_descriptor =
      internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_descriptor.getNestedTypes().get(0);
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_CandleMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_CandleMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_BtcDomCandleMapEntry_descriptor =
      internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_descriptor.getNestedTypes().get(1);
    internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_BtcDomCandleMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateOnlineResponse_BtcDomCandleMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_descriptor,
        new String[] { "BackTestId", "Config", });
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_ConfigEntry_descriptor =
      internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_descriptor.getNestedTypes().get(0);
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_ConfigEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelRequest_ConfigEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetTimeTravelResponse_descriptor,
        new String[] { "BuySell", "TradeMetadata", "ChartList", });
    internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_descriptor,
        new String[] { "OnlineId", "TradeType", "Idx", });
    internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataResponse_descriptor,
        new String[] { "OnlineId", "TradeMetadata", });
    internal_static_coin_algorithm_grpc_service_generated_StreamCandleRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_coin_algorithm_grpc_service_generated_StreamCandleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_StreamCandleRequest_descriptor,
        new String[] { "OnlineId", });
    internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_descriptor,
        new String[] { "Candle", "OnlineId", });
    internal_static_coin_algorithm_grpc_service_generated_GetSignalRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_coin_algorithm_grpc_service_generated_GetSignalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetSignalRequest_descriptor,
        new String[] { "OnlineId", "Idx", });
    internal_static_coin_algorithm_grpc_service_generated_GetSignalResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_coin_algorithm_grpc_service_generated_GetSignalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetSignalResponse_descriptor,
        new String[] { "IsBuy", "IsSell", "IsClose", });
    internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusRequest_descriptor,
        new String[] { "Symbol", "OrderId", });
    internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_GetOrderStatusResponse_descriptor,
        new String[] { "Status", "IsSuccess", "Payload", });
    internal_static_coin_algorithm_grpc_service_generated_CreateOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_coin_algorithm_grpc_service_generated_CreateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateOrderRequest_descriptor,
        new String[] { "OrderId", "Symbol", "Side", "Type", "Price", "Quantity", });
    internal_static_coin_algorithm_grpc_service_generated_CreateOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_coin_algorithm_grpc_service_generated_CreateOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CreateOrderResponse_descriptor,
        new String[] { "OrderId", "Status", "IsSuccess", "Payload", "ExecutedPrice", });
    internal_static_coin_algorithm_grpc_service_generated_CancelOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_coin_algorithm_grpc_service_generated_CancelOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CancelOrderRequest_descriptor,
        new String[] { "OrderId", "Symbol", });
    internal_static_coin_algorithm_grpc_service_generated_CancelOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_coin_algorithm_grpc_service_generated_CancelOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coin_algorithm_grpc_service_generated_CancelOrderResponse_descriptor,
        new String[] { "OrderId", "Status", "IsSuccess", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
