// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface CreateOnlineResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.CreateOnlineResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string onlineId = 1;</code>
   * @return The onlineId.
   */
  String getOnlineId();
  /**
   * <code>string onlineId = 1;</code>
   * @return The bytes for onlineId.
   */
  com.google.protobuf.ByteString
      getOnlineIdBytes();

  /**
   * <code>.coin.algorithm.grpc.service.generated.Candles candles = 2;</code>
   * @return Whether the candles field is set.
   */
  boolean hasCandles();
  /**
   * <code>.coin.algorithm.grpc.service.generated.Candles candles = 2;</code>
   * @return The candles.
   */
  Candles getCandles();
  /**
   * <code>.coin.algorithm.grpc.service.generated.Candles candles = 2;</code>
   */
  CandlesOrBuilder getCandlesOrBuilder();

  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; candleMap = 3;</code>
   */
  int getCandleMapCount();
  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; candleMap = 3;</code>
   */
  boolean containsCandleMap(
      int key);
  /**
   * Use {@link #getCandleMapMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, Candles>
  getCandleMap();
  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; candleMap = 3;</code>
   */
  java.util.Map<Integer, Candles>
  getCandleMapMap();
  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; candleMap = 3;</code>
   */
  /* nullable */
Candles getCandleMapOrDefault(
      int key,
      /* nullable */
Candles defaultValue);
  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; candleMap = 3;</code>
   */
  Candles getCandleMapOrThrow(
      int key);

  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; btcDomCandleMap = 4;</code>
   */
  int getBtcDomCandleMapCount();
  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; btcDomCandleMap = 4;</code>
   */
  boolean containsBtcDomCandleMap(
      int key);
  /**
   * Use {@link #getBtcDomCandleMapMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, Candles>
  getBtcDomCandleMap();
  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; btcDomCandleMap = 4;</code>
   */
  java.util.Map<Integer, Candles>
  getBtcDomCandleMapMap();
  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; btcDomCandleMap = 4;</code>
   */
  /* nullable */
Candles getBtcDomCandleMapOrDefault(
      int key,
      /* nullable */
Candles defaultValue);
  /**
   * <code>map&lt;int32, .coin.algorithm.grpc.service.generated.Candles&gt; btcDomCandleMap = 4;</code>
   */
  Candles getBtcDomCandleMapOrThrow(
      int key);
}
