// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface CreateOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.CreateOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderId = 1;</code>
   * @return The orderId.
   */
  String getOrderId();
  /**
   * <code>string orderId = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>.coin.algorithm.grpc.service.generated.OrderSide side = 3;</code>
   * @return The enum numeric value on the wire for side.
   */
  int getSideValue();
  /**
   * <code>.coin.algorithm.grpc.service.generated.OrderSide side = 3;</code>
   * @return The side.
   */
  OrderSide getSide();

  /**
   * <code>.coin.algorithm.grpc.service.generated.OrderType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.coin.algorithm.grpc.service.generated.OrderType type = 4;</code>
   * @return The type.
   */
  OrderType getType();

  /**
   * <pre>
   * [required] for limit order
   * </pre>
   *
   * <code>string price = 5;</code>
   * @return The price.
   */
  String getPrice();
  /**
   * <pre>
   * [required] for limit order
   * </pre>
   *
   * <code>string price = 5;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string quantity = 6;</code>
   * @return The quantity.
   */
  String getQuantity();
  /**
   * <code>string quantity = 6;</code>
   * @return The bytes for quantity.
   */
  com.google.protobuf.ByteString
      getQuantityBytes();
}
