// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface GetSignalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.GetSignalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isBuy = 1;</code>
   * @return The isBuy.
   */
  boolean getIsBuy();

  /**
   * <code>bool isSell = 2;</code>
   * @return The isSell.
   */
  boolean getIsSell();

  /**
   * <code>bool isClose = 3;</code>
   * @return The isClose.
   */
  boolean getIsClose();
}
