// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface GetSignalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.GetSignalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string onlineId = 1;</code>
   * @return The onlineId.
   */
  String getOnlineId();
  /**
   * <code>string onlineId = 1;</code>
   * @return The bytes for onlineId.
   */
  com.google.protobuf.ByteString
      getOnlineIdBytes();

  /**
   * <code>int32 idx = 2;</code>
   * @return The idx.
   */
  int getIdx();
}
