// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface GetTimeTravelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.GetTimeTravelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Signal signal = 1;</code>
   */
  java.util.List<Signal>
      getSignalList();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Signal signal = 1;</code>
   */
  Signal getSignal(int index);
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Signal signal = 1;</code>
   */
  int getSignalCount();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Signal signal = 1;</code>
   */
  java.util.List<? extends SignalOrBuilder>
      getSignalOrBuilderList();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.Signal signal = 1;</code>
   */
  SignalOrBuilder getSignalOrBuilder(
      int index);

  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.TradeMetadata tradeMetadata = 2;</code>
   */
  java.util.List<TradeMetadata>
      getTradeMetadataList();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.TradeMetadata tradeMetadata = 2;</code>
   */
  TradeMetadata getTradeMetadata(int index);
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.TradeMetadata tradeMetadata = 2;</code>
   */
  int getTradeMetadataCount();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.TradeMetadata tradeMetadata = 2;</code>
   */
  java.util.List<? extends TradeMetadataOrBuilder>
      getTradeMetadataOrBuilderList();
  /**
   * <code>repeated .coin.algorithm.grpc.service.generated.TradeMetadata tradeMetadata = 2;</code>
   */
  TradeMetadataOrBuilder getTradeMetadataOrBuilder(
      int index);

  /**
   * <code>.coin.algorithm.grpc.service.generated.ChartList chartList = 3;</code>
   * @return Whether the chartList field is set.
   */
  boolean hasChartList();
  /**
   * <code>.coin.algorithm.grpc.service.generated.ChartList chartList = 3;</code>
   * @return The chartList.
   */
  ChartList getChartList();
  /**
   * <code>.coin.algorithm.grpc.service.generated.ChartList chartList = 3;</code>
   */
  ChartListOrBuilder getChartListOrBuilder();
}
