// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface GetTradeMetadataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.GetTradeMetadataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string onlineId = 1;</code>
   * @return The onlineId.
   */
  String getOnlineId();
  /**
   * <code>string onlineId = 1;</code>
   * @return The bytes for onlineId.
   */
  com.google.protobuf.ByteString
      getOnlineIdBytes();

  /**
   * <code>.coin.algorithm.grpc.service.generated.TradeMetadata tradeMetadata = 2;</code>
   * @return Whether the tradeMetadata field is set.
   */
  boolean hasTradeMetadata();
  /**
   * <code>.coin.algorithm.grpc.service.generated.TradeMetadata tradeMetadata = 2;</code>
   * @return The tradeMetadata.
   */
  TradeMetadata getTradeMetadata();
  /**
   * <code>.coin.algorithm.grpc.service.generated.TradeMetadata tradeMetadata = 2;</code>
   */
  TradeMetadataOrBuilder getTradeMetadataOrBuilder();
}
