// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface GetTimeTravelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.GetTimeTravelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string backTestId = 1;</code>
   * @return The backTestId.
   */
  String getBackTestId();
  /**
   * <code>string backTestId = 1;</code>
   * @return The bytes for backTestId.
   */
  com.google.protobuf.ByteString
      getBackTestIdBytes();

  /**
   * <code>map&lt;string, string&gt; config = 2;</code>
   */
  int getConfigCount();
  /**
   * <code>map&lt;string, string&gt; config = 2;</code>
   */
  boolean containsConfig(
      String key);
  /**
   * Use {@link #getConfigMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getConfig();
  /**
   * <code>map&lt;string, string&gt; config = 2;</code>
   */
  java.util.Map<String, String>
  getConfigMap();
  /**
   * <code>map&lt;string, string&gt; config = 2;</code>
   */
  /* nullable */
String getConfigOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; config = 2;</code>
   */
  String getConfigOrThrow(
      String key);
}
