// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

/**
 * Protobuf type {@code coin.algorithm.grpc.service.generated.GetTradeMetadataRequest}
 */
public final class GetTradeMetadataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coin.algorithm.grpc.service.generated.GetTradeMetadataRequest)
    GetTradeMetadataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTradeMetadataRequest.newBuilder() to construct.
  private GetTradeMetadataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTradeMetadataRequest() {
    onlineId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTradeMetadataRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CoinService.internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CoinService.internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetTradeMetadataRequest.class, Builder.class);
  }

  public static final int ONLINEID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object onlineId_ = "";
  /**
   * <code>string onlineId = 1;</code>
   * @return The onlineId.
   */
  @Override
  public String getOnlineId() {
    Object ref = onlineId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      onlineId_ = s;
      return s;
    }
  }
  /**
   * <code>string onlineId = 1;</code>
   * @return The bytes for onlineId.
   */
  @Override
  public com.google.protobuf.ByteString
      getOnlineIdBytes() {
    Object ref = onlineId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      onlineId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRADETYPE_FIELD_NUMBER = 2;
  private int tradeType_ = 0;
  /**
   * <pre>
   * [optional] 1: buy, 2: sell, 3: close
   * </pre>
   *
   * <code>int32 tradeType = 2;</code>
   * @return The tradeType.
   */
  @Override
  public int getTradeType() {
    return tradeType_;
  }

  public static final int IDX_FIELD_NUMBER = 3;
  private int idx_ = 0;
  /**
   * <code>int32 idx = 3;</code>
   * @return The idx.
   */
  @Override
  public int getIdx() {
    return idx_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(onlineId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, onlineId_);
    }
    if (tradeType_ != 0) {
      output.writeInt32(2, tradeType_);
    }
    if (idx_ != 0) {
      output.writeInt32(3, idx_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(onlineId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, onlineId_);
    }
    if (tradeType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, tradeType_);
    }
    if (idx_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, idx_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetTradeMetadataRequest)) {
      return super.equals(obj);
    }
    GetTradeMetadataRequest other = (GetTradeMetadataRequest) obj;

    if (!getOnlineId()
        .equals(other.getOnlineId())) return false;
    if (getTradeType()
        != other.getTradeType()) return false;
    if (getIdx()
        != other.getIdx()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ONLINEID_FIELD_NUMBER;
    hash = (53 * hash) + getOnlineId().hashCode();
    hash = (37 * hash) + TRADETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTradeType();
    hash = (37 * hash) + IDX_FIELD_NUMBER;
    hash = (53 * hash) + getIdx();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetTradeMetadataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetTradeMetadataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetTradeMetadataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetTradeMetadataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetTradeMetadataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetTradeMetadataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetTradeMetadataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetTradeMetadataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static GetTradeMetadataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static GetTradeMetadataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetTradeMetadataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetTradeMetadataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetTradeMetadataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code coin.algorithm.grpc.service.generated.GetTradeMetadataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coin.algorithm.grpc.service.generated.GetTradeMetadataRequest)
      GetTradeMetadataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetTradeMetadataRequest.class, Builder.class);
    }

    // Construct using coin.algorithm.grpc.service.GetTradeMetadataRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      onlineId_ = "";
      tradeType_ = 0;
      idx_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_GetTradeMetadataRequest_descriptor;
    }

    @Override
    public GetTradeMetadataRequest getDefaultInstanceForType() {
      return GetTradeMetadataRequest.getDefaultInstance();
    }

    @Override
    public GetTradeMetadataRequest build() {
      GetTradeMetadataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetTradeMetadataRequest buildPartial() {
      GetTradeMetadataRequest result = new GetTradeMetadataRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(GetTradeMetadataRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.onlineId_ = onlineId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tradeType_ = tradeType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.idx_ = idx_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetTradeMetadataRequest) {
        return mergeFrom((GetTradeMetadataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetTradeMetadataRequest other) {
      if (other == GetTradeMetadataRequest.getDefaultInstance()) return this;
      if (!other.getOnlineId().isEmpty()) {
        onlineId_ = other.onlineId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTradeType() != 0) {
        setTradeType(other.getTradeType());
      }
      if (other.getIdx() != 0) {
        setIdx(other.getIdx());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              onlineId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              tradeType_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              idx_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object onlineId_ = "";
    /**
     * <code>string onlineId = 1;</code>
     * @return The onlineId.
     */
    public String getOnlineId() {
      Object ref = onlineId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        onlineId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string onlineId = 1;</code>
     * @return The bytes for onlineId.
     */
    public com.google.protobuf.ByteString
        getOnlineIdBytes() {
      Object ref = onlineId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        onlineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string onlineId = 1;</code>
     * @param value The onlineId to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      onlineId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string onlineId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlineId() {
      onlineId_ = getDefaultInstance().getOnlineId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string onlineId = 1;</code>
     * @param value The bytes for onlineId to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      onlineId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int tradeType_ ;
    /**
     * <pre>
     * [optional] 1: buy, 2: sell, 3: close
     * </pre>
     *
     * <code>int32 tradeType = 2;</code>
     * @return The tradeType.
     */
    @Override
    public int getTradeType() {
      return tradeType_;
    }
    /**
     * <pre>
     * [optional] 1: buy, 2: sell, 3: close
     * </pre>
     *
     * <code>int32 tradeType = 2;</code>
     * @param value The tradeType to set.
     * @return This builder for chaining.
     */
    public Builder setTradeType(int value) {

      tradeType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [optional] 1: buy, 2: sell, 3: close
     * </pre>
     *
     * <code>int32 tradeType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tradeType_ = 0;
      onChanged();
      return this;
    }

    private int idx_ ;
    /**
     * <code>int32 idx = 3;</code>
     * @return The idx.
     */
    @Override
    public int getIdx() {
      return idx_;
    }
    /**
     * <code>int32 idx = 3;</code>
     * @param value The idx to set.
     * @return This builder for chaining.
     */
    public Builder setIdx(int value) {

      idx_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idx = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdx() {
      bitField0_ = (bitField0_ & ~0x00000004);
      idx_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coin.algorithm.grpc.service.generated.GetTradeMetadataRequest)
  }

  // @@protoc_insertion_point(class_scope:coin.algorithm.grpc.service.generated.GetTradeMetadataRequest)
  private static final GetTradeMetadataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetTradeMetadataRequest();
  }

  public static GetTradeMetadataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTradeMetadataRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetTradeMetadataRequest>() {
    @Override
    public GetTradeMetadataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetTradeMetadataRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetTradeMetadataRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public GetTradeMetadataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

