// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface GetTradeMetadataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.GetTradeMetadataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string onlineId = 1;</code>
   * @return The onlineId.
   */
  String getOnlineId();
  /**
   * <code>string onlineId = 1;</code>
   * @return The bytes for onlineId.
   */
  com.google.protobuf.ByteString
      getOnlineIdBytes();

  /**
   * <pre>
   * [optional] 1: buy, 2: sell, 3: closeBuy, 4: closeSell
   * </pre>
   *
   * <code>int32 tradeType = 2;</code>
   * @return The tradeType.
   */
  int getTradeType();

  /**
   * <code>int32 idx = 3;</code>
   * @return The idx.
   */
  int getIdx();
}
