// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface SignalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.Signal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>bool isBuy = 2;</code>
   * @return The isBuy.
   */
  boolean getIsBuy();

  /**
   * <code>bool isSell = 3;</code>
   * @return The isSell.
   */
  boolean getIsSell();

  /**
   * <code>bool isCloseBuy = 4;</code>
   * @return The isCloseBuy.
   */
  boolean getIsCloseBuy();

  /**
   * <code>bool isCloseSell = 5;</code>
   * @return The isCloseSell.
   */
  boolean getIsCloseSell();
}
