// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface StreamCandleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.StreamCandleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
   * @return Whether the candle field is set.
   */
  boolean hasCandle();
  /**
   * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
   * @return The candle.
   */
  Candle getCandle();
  /**
   * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
   */
  CandleOrBuilder getCandleOrBuilder();

  /**
   * <code>string onlineId = 4;</code>
   * @return The onlineId.
   */
  String getOnlineId();
  /**
   * <code>string onlineId = 4;</code>
   * @return The bytes for onlineId.
   */
  com.google.protobuf.ByteString
      getOnlineIdBytes();
}
