// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

/**
 * Protobuf type {@code coin.algorithm.grpc.service.generated.StreamCandleResponse}
 */
public final class StreamCandleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coin.algorithm.grpc.service.generated.StreamCandleResponse)
    StreamCandleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamCandleResponse.newBuilder() to construct.
  private StreamCandleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamCandleResponse() {
    onlineId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamCandleResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CoinService.internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CoinService.internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StreamCandleResponse.class, Builder.class);
  }

  private int bitField0_;
  public static final int CANDLE_FIELD_NUMBER = 1;
  private Candle candle_;
  /**
   * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
   * @return Whether the candle field is set.
   */
  @Override
  public boolean hasCandle() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
   * @return The candle.
   */
  @Override
  public Candle getCandle() {
    return candle_ == null ? Candle.getDefaultInstance() : candle_;
  }
  /**
   * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
   */
  @Override
  public CandleOrBuilder getCandleOrBuilder() {
    return candle_ == null ? Candle.getDefaultInstance() : candle_;
  }

  public static final int ONLINEID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object onlineId_ = "";
  /**
   * <code>string onlineId = 4;</code>
   * @return The onlineId.
   */
  @Override
  public String getOnlineId() {
    Object ref = onlineId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      onlineId_ = s;
      return s;
    }
  }
  /**
   * <code>string onlineId = 4;</code>
   * @return The bytes for onlineId.
   */
  @Override
  public com.google.protobuf.ByteString
      getOnlineIdBytes() {
    Object ref = onlineId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      onlineId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCandle());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(onlineId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, onlineId_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCandle());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(onlineId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, onlineId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StreamCandleResponse)) {
      return super.equals(obj);
    }
    StreamCandleResponse other = (StreamCandleResponse) obj;

    if (hasCandle() != other.hasCandle()) return false;
    if (hasCandle()) {
      if (!getCandle()
          .equals(other.getCandle())) return false;
    }
    if (!getOnlineId()
        .equals(other.getOnlineId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCandle()) {
      hash = (37 * hash) + CANDLE_FIELD_NUMBER;
      hash = (53 * hash) + getCandle().hashCode();
    }
    hash = (37 * hash) + ONLINEID_FIELD_NUMBER;
    hash = (53 * hash) + getOnlineId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StreamCandleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamCandleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamCandleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamCandleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamCandleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamCandleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamCandleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StreamCandleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static StreamCandleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static StreamCandleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StreamCandleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StreamCandleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StreamCandleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code coin.algorithm.grpc.service.generated.StreamCandleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coin.algorithm.grpc.service.generated.StreamCandleResponse)
      StreamCandleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StreamCandleResponse.class, Builder.class);
    }

    // Construct using coin.algorithm.grpc.service.StreamCandleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCandleFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      candle_ = null;
      if (candleBuilder_ != null) {
        candleBuilder_.dispose();
        candleBuilder_ = null;
      }
      onlineId_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_StreamCandleResponse_descriptor;
    }

    @Override
    public StreamCandleResponse getDefaultInstanceForType() {
      return StreamCandleResponse.getDefaultInstance();
    }

    @Override
    public StreamCandleResponse build() {
      StreamCandleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StreamCandleResponse buildPartial() {
      StreamCandleResponse result = new StreamCandleResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(StreamCandleResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.candle_ = candleBuilder_ == null
            ? candle_
            : candleBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.onlineId_ = onlineId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StreamCandleResponse) {
        return mergeFrom((StreamCandleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StreamCandleResponse other) {
      if (other == StreamCandleResponse.getDefaultInstance()) return this;
      if (other.hasCandle()) {
        mergeCandle(other.getCandle());
      }
      if (!other.getOnlineId().isEmpty()) {
        onlineId_ = other.onlineId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCandleFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 34: {
              onlineId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Candle candle_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Candle, Candle.Builder, CandleOrBuilder> candleBuilder_;
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     * @return Whether the candle field is set.
     */
    public boolean hasCandle() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     * @return The candle.
     */
    public Candle getCandle() {
      if (candleBuilder_ == null) {
        return candle_ == null ? Candle.getDefaultInstance() : candle_;
      } else {
        return candleBuilder_.getMessage();
      }
    }
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     */
    public Builder setCandle(Candle value) {
      if (candleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        candle_ = value;
      } else {
        candleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     */
    public Builder setCandle(
        Candle.Builder builderForValue) {
      if (candleBuilder_ == null) {
        candle_ = builderForValue.build();
      } else {
        candleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     */
    public Builder mergeCandle(Candle value) {
      if (candleBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          candle_ != null &&
          candle_ != Candle.getDefaultInstance()) {
          getCandleBuilder().mergeFrom(value);
        } else {
          candle_ = value;
        }
      } else {
        candleBuilder_.mergeFrom(value);
      }
      if (candle_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     */
    public Builder clearCandle() {
      bitField0_ = (bitField0_ & ~0x00000001);
      candle_ = null;
      if (candleBuilder_ != null) {
        candleBuilder_.dispose();
        candleBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     */
    public Candle.Builder getCandleBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCandleFieldBuilder().getBuilder();
    }
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     */
    public CandleOrBuilder getCandleOrBuilder() {
      if (candleBuilder_ != null) {
        return candleBuilder_.getMessageOrBuilder();
      } else {
        return candle_ == null ?
            Candle.getDefaultInstance() : candle_;
      }
    }
    /**
     * <code>.coin.algorithm.grpc.service.generated.Candle candle = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Candle, Candle.Builder, CandleOrBuilder>
        getCandleFieldBuilder() {
      if (candleBuilder_ == null) {
        candleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Candle, Candle.Builder, CandleOrBuilder>(
                getCandle(),
                getParentForChildren(),
                isClean());
        candle_ = null;
      }
      return candleBuilder_;
    }

    private Object onlineId_ = "";
    /**
     * <code>string onlineId = 4;</code>
     * @return The onlineId.
     */
    public String getOnlineId() {
      Object ref = onlineId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        onlineId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string onlineId = 4;</code>
     * @return The bytes for onlineId.
     */
    public com.google.protobuf.ByteString
        getOnlineIdBytes() {
      Object ref = onlineId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        onlineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string onlineId = 4;</code>
     * @param value The onlineId to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      onlineId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string onlineId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlineId() {
      onlineId_ = getDefaultInstance().getOnlineId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string onlineId = 4;</code>
     * @param value The bytes for onlineId to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      onlineId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coin.algorithm.grpc.service.generated.StreamCandleResponse)
  }

  // @@protoc_insertion_point(class_scope:coin.algorithm.grpc.service.generated.StreamCandleResponse)
  private static final StreamCandleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StreamCandleResponse();
  }

  public static StreamCandleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamCandleResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamCandleResponse>() {
    @Override
    public StreamCandleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamCandleResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StreamCandleResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public StreamCandleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

