// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

/**
 * Protobuf type {@code coin.algorithm.grpc.service.generated.TradeMetadata}
 */
public final class TradeMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coin.algorithm.grpc.service.generated.TradeMetadata)
    TradeMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TradeMetadata.newBuilder() to construct.
  private TradeMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TradeMetadata() {
    tradeLog_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TradeMetadata();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CoinService.internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CoinService.internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TradeMetadata.class, Builder.class);
  }

  public static final int PRICE_FIELD_NUMBER = 1;
  private double price_ = 0D;
  /**
   * <code>double price = 1;</code>
   * @return The price.
   */
  @Override
  public double getPrice() {
    return price_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 2;
  private double amount_ = 0D;
  /**
   * <code>double amount = 2;</code>
   * @return The amount.
   */
  @Override
  public double getAmount() {
    return amount_;
  }

  public static final int TAKEPROFITPRICE_FIELD_NUMBER = 3;
  private double takeProfitPrice_ = 0D;
  /**
   * <code>double takeProfitPrice = 3;</code>
   * @return The takeProfitPrice.
   */
  @Override
  public double getTakeProfitPrice() {
    return takeProfitPrice_;
  }

  public static final int TAKESTOPLOSSPRICE_FIELD_NUMBER = 4;
  private double takeStopLossPrice_ = 0D;
  /**
   * <code>double takeStopLossPrice = 4;</code>
   * @return The takeStopLossPrice.
   */
  @Override
  public double getTakeStopLossPrice() {
    return takeStopLossPrice_;
  }

  public static final int TRADELOG_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object tradeLog_ = "";
  /**
   * <code>string tradeLog = 5;</code>
   * @return The tradeLog.
   */
  @Override
  public String getTradeLog() {
    Object ref = tradeLog_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tradeLog_ = s;
      return s;
    }
  }
  /**
   * <code>string tradeLog = 5;</code>
   * @return The bytes for tradeLog.
   */
  @Override
  public com.google.protobuf.ByteString
      getTradeLogBytes() {
    Object ref = tradeLog_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tradeLog_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WAITINGMINUTES_FIELD_NUMBER = 6;
  private long waitingMinutes_ = 0L;
  /**
   * <code>int64 waitingMinutes = 6;</code>
   * @return The waitingMinutes.
   */
  @Override
  public long getWaitingMinutes() {
    return waitingMinutes_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(1, price_);
    }
    if (Double.doubleToRawLongBits(amount_) != 0) {
      output.writeDouble(2, amount_);
    }
    if (Double.doubleToRawLongBits(takeProfitPrice_) != 0) {
      output.writeDouble(3, takeProfitPrice_);
    }
    if (Double.doubleToRawLongBits(takeStopLossPrice_) != 0) {
      output.writeDouble(4, takeStopLossPrice_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tradeLog_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tradeLog_);
    }
    if (waitingMinutes_ != 0L) {
      output.writeInt64(6, waitingMinutes_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, price_);
    }
    if (Double.doubleToRawLongBits(amount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, amount_);
    }
    if (Double.doubleToRawLongBits(takeProfitPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, takeProfitPrice_);
    }
    if (Double.doubleToRawLongBits(takeStopLossPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, takeStopLossPrice_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tradeLog_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tradeLog_);
    }
    if (waitingMinutes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, waitingMinutes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TradeMetadata)) {
      return super.equals(obj);
    }
    TradeMetadata other = (TradeMetadata) obj;

    if (Double.doubleToLongBits(getPrice())
        != Double.doubleToLongBits(
            other.getPrice())) return false;
    if (Double.doubleToLongBits(getAmount())
        != Double.doubleToLongBits(
            other.getAmount())) return false;
    if (Double.doubleToLongBits(getTakeProfitPrice())
        != Double.doubleToLongBits(
            other.getTakeProfitPrice())) return false;
    if (Double.doubleToLongBits(getTakeStopLossPrice())
        != Double.doubleToLongBits(
            other.getTakeStopLossPrice())) return false;
    if (!getTradeLog()
        .equals(other.getTradeLog())) return false;
    if (getWaitingMinutes()
        != other.getWaitingMinutes()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getAmount()));
    hash = (37 * hash) + TAKEPROFITPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getTakeProfitPrice()));
    hash = (37 * hash) + TAKESTOPLOSSPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getTakeStopLossPrice()));
    hash = (37 * hash) + TRADELOG_FIELD_NUMBER;
    hash = (53 * hash) + getTradeLog().hashCode();
    hash = (37 * hash) + WAITINGMINUTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWaitingMinutes());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TradeMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TradeMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TradeMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TradeMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TradeMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TradeMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TradeMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TradeMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static TradeMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static TradeMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TradeMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TradeMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TradeMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code coin.algorithm.grpc.service.generated.TradeMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coin.algorithm.grpc.service.generated.TradeMetadata)
      TradeMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TradeMetadata.class, Builder.class);
    }

    // Construct using coin.algorithm.grpc.service.TradeMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      price_ = 0D;
      amount_ = 0D;
      takeProfitPrice_ = 0D;
      takeStopLossPrice_ = 0D;
      tradeLog_ = "";
      waitingMinutes_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CoinService.internal_static_coin_algorithm_grpc_service_generated_TradeMetadata_descriptor;
    }

    @Override
    public TradeMetadata getDefaultInstanceForType() {
      return TradeMetadata.getDefaultInstance();
    }

    @Override
    public TradeMetadata build() {
      TradeMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TradeMetadata buildPartial() {
      TradeMetadata result = new TradeMetadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(TradeMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.takeProfitPrice_ = takeProfitPrice_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.takeStopLossPrice_ = takeStopLossPrice_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tradeLog_ = tradeLog_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.waitingMinutes_ = waitingMinutes_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TradeMetadata) {
        return mergeFrom((TradeMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TradeMetadata other) {
      if (other == TradeMetadata.getDefaultInstance()) return this;
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      if (other.getTakeProfitPrice() != 0D) {
        setTakeProfitPrice(other.getTakeProfitPrice());
      }
      if (other.getTakeStopLossPrice() != 0D) {
        setTakeStopLossPrice(other.getTakeStopLossPrice());
      }
      if (!other.getTradeLog().isEmpty()) {
        tradeLog_ = other.tradeLog_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getWaitingMinutes() != 0L) {
        setWaitingMinutes(other.getWaitingMinutes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              price_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              amount_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              takeProfitPrice_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              takeStopLossPrice_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 42: {
              tradeLog_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              waitingMinutes_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double price_ ;
    /**
     * <code>double price = 1;</code>
     * @return The price.
     */
    @Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 1;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {

      price_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000001);
      price_ = 0D;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <code>double amount = 2;</code>
     * @return The amount.
     */
    @Override
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 2;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(double value) {

      amount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      amount_ = 0D;
      onChanged();
      return this;
    }

    private double takeProfitPrice_ ;
    /**
     * <code>double takeProfitPrice = 3;</code>
     * @return The takeProfitPrice.
     */
    @Override
    public double getTakeProfitPrice() {
      return takeProfitPrice_;
    }
    /**
     * <code>double takeProfitPrice = 3;</code>
     * @param value The takeProfitPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTakeProfitPrice(double value) {

      takeProfitPrice_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double takeProfitPrice = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTakeProfitPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      takeProfitPrice_ = 0D;
      onChanged();
      return this;
    }

    private double takeStopLossPrice_ ;
    /**
     * <code>double takeStopLossPrice = 4;</code>
     * @return The takeStopLossPrice.
     */
    @Override
    public double getTakeStopLossPrice() {
      return takeStopLossPrice_;
    }
    /**
     * <code>double takeStopLossPrice = 4;</code>
     * @param value The takeStopLossPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTakeStopLossPrice(double value) {

      takeStopLossPrice_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double takeStopLossPrice = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTakeStopLossPrice() {
      bitField0_ = (bitField0_ & ~0x00000008);
      takeStopLossPrice_ = 0D;
      onChanged();
      return this;
    }

    private Object tradeLog_ = "";
    /**
     * <code>string tradeLog = 5;</code>
     * @return The tradeLog.
     */
    public String getTradeLog() {
      Object ref = tradeLog_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tradeLog_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tradeLog = 5;</code>
     * @return The bytes for tradeLog.
     */
    public com.google.protobuf.ByteString
        getTradeLogBytes() {
      Object ref = tradeLog_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tradeLog_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tradeLog = 5;</code>
     * @param value The tradeLog to set.
     * @return This builder for chaining.
     */
    public Builder setTradeLog(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      tradeLog_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string tradeLog = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeLog() {
      tradeLog_ = getDefaultInstance().getTradeLog();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string tradeLog = 5;</code>
     * @param value The bytes for tradeLog to set.
     * @return This builder for chaining.
     */
    public Builder setTradeLogBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tradeLog_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long waitingMinutes_ ;
    /**
     * <code>int64 waitingMinutes = 6;</code>
     * @return The waitingMinutes.
     */
    @Override
    public long getWaitingMinutes() {
      return waitingMinutes_;
    }
    /**
     * <code>int64 waitingMinutes = 6;</code>
     * @param value The waitingMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setWaitingMinutes(long value) {

      waitingMinutes_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 waitingMinutes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearWaitingMinutes() {
      bitField0_ = (bitField0_ & ~0x00000020);
      waitingMinutes_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coin.algorithm.grpc.service.generated.TradeMetadata)
  }

  // @@protoc_insertion_point(class_scope:coin.algorithm.grpc.service.generated.TradeMetadata)
  private static final TradeMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TradeMetadata();
  }

  public static TradeMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradeMetadata>
      PARSER = new com.google.protobuf.AbstractParser<TradeMetadata>() {
    @Override
    public TradeMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TradeMetadata> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TradeMetadata> getParserForType() {
    return PARSER;
  }

  @Override
  public TradeMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

