// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin_service.proto

// Protobuf Java Version: 3.25.1
package coin.algorithm.grpc.service;

public interface TradeMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coin.algorithm.grpc.service.generated.TradeMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double price = 1;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>double amount = 2;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>double takeProfitPrice = 3;</code>
   * @return The takeProfitPrice.
   */
  double getTakeProfitPrice();

  /**
   * <code>double takeStopLossPrice = 4;</code>
   * @return The takeStopLossPrice.
   */
  double getTakeStopLossPrice();

  /**
   * <code>string tradeLog = 5;</code>
   * @return The tradeLog.
   */
  String getTradeLog();
  /**
   * <code>string tradeLog = 5;</code>
   * @return The bytes for tradeLog.
   */
  com.google.protobuf.ByteString
      getTradeLogBytes();

  /**
   * <code>int64 waitingMinutes = 6;</code>
   * @return The waitingMinutes.
   */
  long getWaitingMinutes();
}
